import "server-only";
import crypto from "node:crypto";

/**
 * Admin authentication: password + TOTP, both required.
 *
 * Two-factor is not optional here. This surface can change what every product
 * on the store costs, so a single stolen password must not be enough to reach
 * it — a leaked password alone gets an attacker to the second prompt and no
 * further.
 *
 * No dependencies: scrypt and HMAC-SHA1 are both in Node's standard library, so
 * there is no bcrypt/otplib supply chain attached to the most sensitive part of
 * the app.
 *
 * Nothing here is ever stored in the repository. The password hash and the TOTP
 * secret live in environment variables, generated by `npm run admin:setup`.
 */

/* -------------------------------------------------------------------------
   Password — scrypt
   ------------------------------------------------------------------------- */

const SCRYPT_PARAMS = { N: 16384, r: 8, p: 1, keylen: 64 } as const;

/** Format: `scrypt$<saltHex>$<hashHex>`. */
export function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16);
  const hash = crypto.scryptSync(password.normalize("NFKC"), salt, SCRYPT_PARAMS.keylen, {
    N: SCRYPT_PARAMS.N,
    r: SCRYPT_PARAMS.r,
    p: SCRYPT_PARAMS.p,
  });
  return `scrypt$${salt.toString("hex")}$${hash.toString("hex")}`;
}

export function verifyPassword(password: string, stored: string): boolean {
  const parts = stored.split("$");
  if (parts.length !== 3 || parts[0] !== "scrypt") return false;

  const salt = Buffer.from(parts[1]!, "hex");
  const expected = Buffer.from(parts[2]!, "hex");
  if (salt.length === 0 || expected.length === 0) return false;

  let actual: Buffer;
  try {
    actual = crypto.scryptSync(password.normalize("NFKC"), salt, expected.length, {
      N: SCRYPT_PARAMS.N,
      r: SCRYPT_PARAMS.r,
      p: SCRYPT_PARAMS.p,
    });
  } catch {
    return false;
  }

  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}

/* -------------------------------------------------------------------------
   TOTP — RFC 6238, the algorithm every authenticator app implements
   ------------------------------------------------------------------------- */

const BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

export function generateTotpSecret(): string {
  const bytes = crypto.randomBytes(20); // 160 bits, per RFC 4226
  let bits = "";
  for (const byte of bytes) bits += byte.toString(2).padStart(8, "0");

  let out = "";
  for (let i = 0; i + 5 <= bits.length; i += 5) {
    out += BASE32_ALPHABET[parseInt(bits.slice(i, i + 5), 2)];
  }
  return out;
}

function base32Decode(input: string): Buffer {
  const clean = input.toUpperCase().replace(/=+$/, "").replace(/\s/g, "");
  let bits = "";
  for (const char of clean) {
    const index = BASE32_ALPHABET.indexOf(char);
    if (index === -1) throw new Error("Invalid base32 character in TOTP secret");
    bits += index.toString(2).padStart(5, "0");
  }
  const bytes: number[] = [];
  for (let i = 0; i + 8 <= bits.length; i += 8) {
    bytes.push(parseInt(bits.slice(i, i + 8), 2));
  }
  return Buffer.from(bytes);
}

/** The 6-digit code for a given 30-second time step. */
function totpAt(secret: string, counter: number): string {
  const key = base32Decode(secret);

  const buffer = Buffer.alloc(8);
  buffer.writeBigUInt64BE(BigInt(counter));

  const digest = crypto.createHmac("sha1", key).update(buffer).digest();
  // Dynamic truncation, RFC 4226 §5.4.
  const offset = digest[digest.length - 1]! & 0x0f;
  const binary =
    ((digest[offset]! & 0x7f) << 24) |
    ((digest[offset + 1]! & 0xff) << 16) |
    ((digest[offset + 2]! & 0xff) << 8) |
    (digest[offset + 3]! & 0xff);

  return String(binary % 1_000_000).padStart(6, "0");
}

/**
 * Verify a TOTP code.
 *
 * A ±1 step window absorbs clock drift between the phone and the server. Wider
 * than that starts meaningfully extending how long a shoulder-surfed code stays
 * usable, so one step each way is the standard trade.
 */
export function verifyTotp(code: string, secret: string, window = 1): boolean {
  const normalised = code.replace(/\D/g, "");
  if (normalised.length !== 6) return false;

  const step = Math.floor(Date.now() / 1000 / 30);
  for (let drift = -window; drift <= window; drift++) {
    const candidate = totpAt(secret, step + drift);
    // Timing-safe even here: a fast reject leaks which digits matched.
    if (
      candidate.length === normalised.length &&
      crypto.timingSafeEqual(Buffer.from(candidate), Buffer.from(normalised))
    ) {
      return true;
    }
  }
  return false;
}

/** The `otpauth://` URI an authenticator app scans. */
export function totpUri(secret: string, account: string, issuer = "L'INDIENNE"): string {
  const label = encodeURIComponent(`${issuer}:${account}`);
  const params = new URLSearchParams({
    secret,
    issuer,
    algorithm: "SHA1",
    digits: "6",
    period: "30",
  });
  return `otpauth://totp/${label}?${params.toString()}`;
}

/* -------------------------------------------------------------------------
   Sessions — signed, stateless
   ------------------------------------------------------------------------- */

export const ADMIN_COOKIE = "lindienne_admin";
const SESSION_TTL_MS = 8 * 60 * 60 * 1000; // one working day

interface SessionPayload {
  sub: string;
  exp: number;
}

function sessionSecret(): string {
  const secret = process.env.ADMIN_SESSION_SECRET ?? process.env.ORDER_SIGNING_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error(
      "ADMIN_SESSION_SECRET (or ORDER_SIGNING_SECRET) must be at least 32 characters.",
    );
  }
  return secret;
}

export function createSession(subject: string): { value: string; maxAge: number } {
  const payload: SessionPayload = { sub: subject, exp: Date.now() + SESSION_TTL_MS };
  const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signature = crypto
    .createHmac("sha256", sessionSecret())
    .update(encoded)
    .digest("base64url");
  return { value: `${encoded}.${signature}`, maxAge: SESSION_TTL_MS / 1000 };
}

export function readSession(token: string | undefined): SessionPayload | null {
  if (!token) return null;

  const parts = token.split(".");
  if (parts.length !== 2) return null;
  const [encoded, signature] = parts as [string, string];

  let expected: string;
  try {
    expected = crypto.createHmac("sha256", sessionSecret()).update(encoded).digest("base64url");
  } catch {
    return null;
  }

  const given = Buffer.from(signature);
  const want = Buffer.from(expected);
  if (given.length !== want.length || !crypto.timingSafeEqual(given, want)) return null;

  try {
    const payload = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")) as SessionPayload;
    if (typeof payload.exp !== "number" || payload.exp < Date.now()) return null;
    return payload;
  } catch {
    return null;
  }
}

/* -------------------------------------------------------------------------
   Configuration
   ------------------------------------------------------------------------- */

export interface AdminConfig {
  email: string;
  passwordHash: string;
  totpSecret: string;
}

/**
 * Read admin credentials from the environment.
 *
 * Returns null when any part is missing, which the routes treat as "the admin
 * is switched off" — a 404, not a login page. An admin surface that advertises
 * itself while being unconfigured is an invitation.
 */
export function getAdminConfig(): AdminConfig | null {
  const email = process.env.ADMIN_EMAIL;
  const passwordHash = process.env.ADMIN_PASSWORD_HASH;
  const totpSecret = process.env.ADMIN_TOTP_SECRET;

  if (!email || !passwordHash || !totpSecret) return null;
  if (!passwordHash.startsWith("scrypt$")) return null;

  return { email, passwordHash, totpSecret };
}

export function isAdminEnabled(): boolean {
  return getAdminConfig() !== null;
}
